language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: iC6B2bX+EFlzDcKMjwm0ubojKaL2YFseXiqc9yszxsgY/3tbbLY1Wb6wRcpsJeaotBf1ii6ordfWacNnKH8+DU19XE5fR4hWhD8a5SljCWLSC5InzzXYSrs8h4TJFWHPc2zlFpH5Qfdi3LGJOUPHE5FyFyoOY21EGR2o2WYEncGvggJAfqHgQYijxjVBqmtGQ294zJxAUldw4ClzrGM+uQFTSVFpffxqU/Gb1O80DMNgYYCVzLXG4Y+vvCUx4VJqGargFYNXNsN04kvHjf+lG3C2SUIJKbLt/fBaTzB9ncd2UW9X0sk/nTZPdoPTAbdtOjsyj05e8tWb8giFQ/PU8crKfn52YT5hIZLd0HIHZXc7+TaRGGbA1ZrmYN6K1FPnW8wcsgm3woioVrjWVX6UCpemC9cp9MYDqHITzE8r1Gj7jWOzbnCUFW+aOCtR9RmMF8PB8eTt9BU4Jn0tLx0l7ulsUSqPA6SwKl8iGR2Mhq18TFleZ2kk9wxieSeqGV44MXcWYlYQqxyf8aAvPYxge3uVMlgQxJbaQyM1jYNcmVyFaeXp8UMrptPeK/WyIEhalat4hS/2NJXAdES4wgWsIbYF1Gu7YqK4vH5VGYWyjGodkKBgqp9frWzaSz1AvwiHaeOnZtb3H2hF08MLePT81z3OWZXvC4mA+0qTpulW+KA=
  app: peaceful-waters-13139
  on:
    repo: zephitez/serveAPI
